#!/usr/bin/env bash
# Configures /etc/hosts:
# - localhost -> 127.0.0.2
# - facebook.com -> 8.8.8.8

HOSTS="/etc/hosts"

# Remove any IPv4 lines that contain "localhost"
sed -i '/^127\.[0-9.]*[[:space:]].*\blocalhost\b/d' "$HOSTS"

# Remove any existing facebook.com line (anywhere)
sed -i '/[[:space:]]facebook\.com\([[:space:]]\|$\)/d' "$HOSTS"

# Add required mappings
echo "127.0.0.2 localhost" >> "$HOSTS"
echo "8.8.8.8 facebook.com" >> "$HOSTS"