#!/usr/bin/env bash
# Configures /etc/hosts:
# - localhost -> 127.0.0.2
# - facebook.com -> 8.8.8.8

{
  printf '127.0.0.2 localhost\n'
  printf '8.8.8.8 facebook.com\n'
  cat /etc/hosts
} | tee /etc/hosts >/dev/null